apiVersion: v1
kind: Service
metadata:
  name: jenkins-master
  labels:
    app: jenkins
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - port: 8080
    name: web-front
  - port: 50000
    name: slave-port
  selector:
    app: jenkins
