apiVersion: v1
kind: ReplicationController
metadata:
  name: jenkins-master
  # these labels can be applied automatically
  # from the labels in the pod template if not set
  labels:
    app: jenkins
    role: master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins
        role: master
    spec:
      containers:
      - name: master
        image: gcr.io/kubernetes-codelab-1300/jenkins-master:1.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-home
        ports:
          - containerPort: 8080
          - containerPort: 50000
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 5
      volumes:
      - name: jenkins-home
        gcePersistentDisk:
          pdName: jenkins-data-jenkins-lab
          fsType: ext4
